/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Antonio' at '03/02/15 2:29 PM' with Gradle 2.2.1
 *
 * @author Antonio, @date 03/02/15 2:29 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
